# Site settings
title: 'EBHC Group | Education, Training & Implementation'
email: ebhcgroup@gmail.com
description: The Evidence-based Health Care Group is an educational collaborative that provides customized consultation to organizations interested in implementing evidence-based health care.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ebhcgroup.github.io" # the base hostname & protocol for your site
github_username:  ebhcgroup

# Build settings
markdown: kramdown
permalink: /:categories/:title.html

gems:
- jekyll-compass